apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: dummy # from-param: ${service_name}
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    spec:
      containers:
        - name: backend
          image: backend
