apiVersion: skaffold/v3
kind: Config
metadata:
  name: "my-cloud-end-point-backend"
build:
  tagPolicy:
    envTemplate:
      template: "{{ .APP_VERSION }}"
  artifacts:
    - image: backend
      context: ..
      docker:
        buildArgs:
          app_version: "{{ .APP_VERSION }}"
        dockerfile: ../Dockerfile
  local:
    useBuildkit: true
    push: true
deploy:
  cloudrun: {}
manifests:
  rawYaml:
    - manifest.yaml
